### ISSUE TITLE
RadioButton Group and CheckBox Group

### ISSUE THREAD

**Issue by Jos1k** [kevinchappell/formBuilder#10]
Hi, I have some problems with groups (checkbox and radiobutton). All changes aren't showing on UI after editing and aren't saving to XML. 
This problem even present on your demo.
Maybe I'm doing smth wrong?

**Comment by kevinchappell** [comment]
I look into it

**Comment by Jos1k** [comment]
Thx for fast answer :+1:

**Comment by kevinchappell** [comment]
Resolved with https://github.com/kevinchappell/formBuilder/pull/11

**Comment by Jos1k** [comment]
Thank you you for fast fix. It's really cool!!
It's currently adding options to XML, but looks like still don't show changes on UI. Is it okay?

**Comment by kevinchappell** [comment]
Good catch, I'll include that in a separate fix.

On Thu, Oct 15, 2015 at 1:41 PM, Ihor Hadzera <notifications@github.com>
wrote:

> Thank you you for fast fix. It's really cool!!
> It's currently adding options to XML, but looks like still don't show
> changes on UI. Is it okay?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kevinchappell/formBuilder/issues/10#issuecomment-148373647>
> .
>



-- 
*Kevin Chappell*
US - 860.577.2696
PT - 96.970.1158
