### ISSUE TITLE
urgent: bower package not found

### ISSUE THREAD

**Issue by lzheng5** [kevinchappell/formBuilder#332]
Hi,

When trying to install `formBuilder` from `bower`, I got the following error.

```
bower formBuilder#~1.24.2       cached https://github.com/kevinchappell/formBuilder.git#1.24.3
bower formBuilder#~1.24.2     validate 1.24.3 against https://github.com/kevinchappell/formBuilder.git#~1.24.2
bower jquery#^3.1.1             cached https://github.com/jquery/jquery-dist.git#3.1.1
bower jquery#^3.1.1           validate 3.1.1 against https://github.com/jquery/jquery-dist.git#^3.1.1
bower                        ENOTFOUND Package jQuery UI Sortable=jquery-ui-sortable not found
```

I looked into the `bower.json` file and found the following line.
```
"jQuery UI Sortable": "jquery-ui-sortable#*"
```
Not sure what is going on here. Also I am be able to install `jquery-ui-sortable` but not `jQuery UI Sortable`, which is the name. See [here](https://github.com/ryantbrown/jquery-ui-sortable/blob/master/bower.json).

Thanks,

**Comment by SHBelsky** [comment]
+1, I get the same error. From what I understand, the existing bower.json is pointing to the wrong Bower package. Changing it will probably fix it.

**Comment by SHBelsky** [comment]
Fixed in #340

**Comment by Iyashu5040** [comment]
Any idea when the fix is going to be released? I'm still getting this error with what I'm assuming is the latest  version `1.24.3`
