### ISSUE TITLE
Multiple TinyMCE issue

### ISSUE THREAD

**Issue by DnnDeveloper** [kevinchappell/formBuilder#732]
### Description: Multiple TinyMCE on the form not properly rendering the second/other instances, the Second instance of TinyMCE editor not allowing to enter/edit the content.

If we add the multiple TinyMCE on the form it shows the second instance's TinyMCE iframe into the first instance of TinyMCE.  It does not happen every time when page loading. JSON form data never get change but in sometimes ID of text area/TinyMCE get's change/swap. I tried with assigning the selector for the TinyMCE while prototype.configure.

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Google Chrome (Version 65.0.3325.181 (Official Build) (64-bit))
 - OS: Windows 10

### Screenshot - *(optional)* 
![image](https://user-images.githubusercontent.com/37218548/38012427-13bde3fa-327f-11e8-9091-5180700f4a38.png)

![image](https://user-images.githubusercontent.com/37218548/38012458-35892e90-327f-11e8-97df-ec3ad01b2658.png)

Thank you!

**Comment by wolfej1994** [comment]
Same issue here, also when I move the tinyMCE editor it clears all content.

**Comment by DocCheese** [comment]
Also have same issue, any resolution timeline?

**Comment by DocCheese** [comment]
@kevinchappell I know that the issue that is the form is loading multiple times with the same IDs for everything, however I don't know the code well enough to see to fix it. PLEASE PLEASE PLEASE look into this because I could desperately use this for my latest project.

Thanks you.

**Comment by kevinchappell** [comment]
sorry guys, i havent had time to get into this. @DocCheese can you confirm youre still seeing this in current version? this issue was opened against 2.9.8 and formBuilder is now at 3.2.3

**Comment by DocCheese** [comment]
Hey @kevinchappell so the version of FormBuilder I was using was from pre v3 it turns out. It was part of a Laravel Framework / FormBuilder Package that someone released (jazmy/laravel-formbuilder). I was able to update their version to work with your latest version and it did fix the issue. However it did open up another. 

--

If you use a TinyMCE text area and need to place any predefined text inside it while building the form (For example if you need to have a table inside)- all content will get deleted if you at any point click the  edit element button for that element. Anything typed inside is completely reset. 

This is SO close to being exactly what I need for a project I'm working on. Please advice.

PS. I also tried to see if it would work with TInyMCE v5 and while it sort of does, the issue is only the buttons on the top-most form will actually work. I'm looking to use v4 to this is not a big deal for me, just letting you know.

Thanks!
-Drew

**Comment by kevinchappell** [comment]
@DnnDeveloper Thanks for the feedback about tinyMCE v5 and verifying the original issue is fixed. It sounds like the editor is being reinitialized without the existing value. We should prevent reinitialization or initialize with the value. 

It might be a few days before I can get to this but it sounds like it should be a fairly simple fix. Maybe we should just return if [this condition](https://github.com/kevinchappell/formBuilder/blob/master/src/js/control/textarea.tinymce.js#L75) is true instead of rebuilding the editor

**Comment by DocCheese** [comment]
@kevinchappell Regrettably it seems like I'm still getting the initial multiple TinyMCE block issue. It is just not consistent on when it occurs.

**Comment by ashishmit14** [comment]
@kevinchappell  Same issue I was facing since more than 1 year. Recently I have found a fix and hope it will help to those who are willing to use tinymce editors whatsoever be the reason.
In formbuilder, I have changed the textarea subtype from tinymce to textarea. 
Here you can use a keyword which will start the ID string, specific to the form.
Then while rendering, get all textarea IDs starting with the keyword. Loop through and use 
tinymce .init().

While this fixes the rendering issue, but comes with some headache of setting and getting values to/from the tinymce editor.
But works well if you are willing to do the extra typings.
I have used the formbuilder with Vue JS.
I am a newbie, please guide me if anything goes wrong, with the mentioned approach.

**Comment by prod-cnd** [comment]
I confirm this problem. I also cannot find a solution, but I can indicate the tests that I have carried out:
When I load 2 textarea
defaultFields :[
{"type":"textarea","subtype":"tinymce","required":false,"label":"Text Area","className":"form-control","name":"textarea-1584632106879","access":false,"value":"<p>test 1</p>"},
{"type":"textarea","subtype":"tinymce","required":false,"label":"Text Area","className":"form-control","name":"textarea-1584632412367","access":false,"value":"<p>test 2</p>"}
]

=> I have two contents (test 1 and test 2) which appear in the TinyMCE of the first field. It looks like TinyMCE is initialized on the first textarea and that the content of the second field is loaded in the first TinyMCE.
Maybe a variable (id or other) is identical in the 2 TinyMCE.

=> When editing the textarea, content 1 is in textarea 1 and content 2 in textarea 2

=> When we return to TinyMCE display, the content returns to its place. Content 1 in textarea 1 and content 2 in textarea 2. So there seems to be a bug in the display of content.
I think that to go from the edition mode to the display of TinyMCE, must reset tinyMCE and remove the bug.

If a new text is added, the content 3 is displayed correctly. If the page is saved and reloaded, the 3: tinyMCE will load, and the contents 1, 2 and 3 will appear in field 1. The textarea 2 and 3 appear empty. In reality, they are not empty (the content is present), but the display of the content shifts.

Besides formBuilder, I loaded 2 textarea with content. The 2 textarea load TinyCME well.

The problem seems to come from an initialization of tinyMCE which is not done each time the textarea is loaded.

**Comment by prod-cnd** [comment]
@kevinchappell 
Ok I go ahead ... When we load the page with 2 tinymce, we see that all the ids of tinymce are identical. When you edit the textarea and return to tinymce, the Ids change.
The iframe with content 2 is loaded into the id of the first content.
it is therefore necessary when the content loads with the 2 tinymce, that the IDs change each time tinyMCE is loaded.
If anyone has an idea to change the ID
![BUG ID](https://user-images.githubusercontent.com/18213505/77096200-47360e00-6a0f-11ea-9f50-ea00279541c2.jpg)

**Comment by prod-cnd** [comment]
I just set up a codepen with the code : [https://codepen.io/prod-cnd/pen/RwPBXaw](url)

**Comment by Jojoshua** [comment]
I think I observed this as well and fixed in the pending pr. Try these scripts
 https://github.com/kevinchappell/formBuilder/pull/1243#issuecomment-1067496816

**Comment by Jojoshua** [comment]
3.8 is now released and should fix the issue. Feel free to reopen if not the case.
